server:
  port: 8083

spring:
  application:
    name: rating-service   # Moved this to the correct level
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: microservices
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
