server:
  port: 8082

spring:
  application:
    name: hotel-service   # Moved this to the correct level
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices?serverTimezone=UTC
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true